# global config
global:
  scrape_interval: 45s # Set the scrape interval to every 45 seconds. Default is every 1 minute.
  scrape_timeout: 30s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    origin_prometheus: mktxp

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['panopticon.local:9090']

  - job_name: 'grafana'
    static_configs:
    - targets: ['panopticon.local:3000']

  - job_name: 'loki'
    static_configs:
    - targets: ['panopticon.local:3100']

  - job_name: 'promtail'
    static_configs:
    - targets: ['panopticon.local:9080']

  - job_name: 'mktxp'
    static_configs:
      - targets: ['mktxp:49090']

  - job_name: 'ping'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets:
      - panopticon.local:9427

  - job_name: 'truenas-graphite'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets:
      - panopticon.local:9108

  - job_name: 'node'
    static_configs:
     - targets: ['panopticon.local:9100']
